// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// ddist_univ
double ddist_univ(double dY, arma::vec vTheta, std::string dist, bool bLog);
RcppExport SEXP GAS_ddist_univ(SEXP dYSEXP, SEXP vThetaSEXP, SEXP distSEXP, SEXP bLogSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type dY(dYSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type vTheta(vThetaSEXP);
    Rcpp::traits::input_parameter< std::string >::type dist(distSEXP);
    Rcpp::traits::input_parameter< bool >::type bLog(bLogSEXP);
    __result = Rcpp::wrap(ddist_univ(dY, vTheta, dist, bLog));
    return __result;
END_RCPP
}
// IM_univ
arma::mat IM_univ(arma::vec vTheta, std::string Dist);
RcppExport SEXP GAS_IM_univ(SEXP vThetaSEXP, SEXP DistSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::vec >::type vTheta(vThetaSEXP);
    Rcpp::traits::input_parameter< std::string >::type Dist(DistSEXP);
    __result = Rcpp::wrap(IM_univ(vTheta, Dist));
    return __result;
END_RCPP
}
// Score_univ
arma::vec Score_univ(double dY, arma::vec vTheta, std::string dist);
RcppExport SEXP GAS_Score_univ(SEXP dYSEXP, SEXP vThetaSEXP, SEXP distSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type dY(dYSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type vTheta(vThetaSEXP);
    Rcpp::traits::input_parameter< std::string >::type dist(distSEXP);
    __result = Rcpp::wrap(Score_univ(dY, vTheta, dist));
    return __result;
END_RCPP
}
