# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mWCRPS_backtest <- function(vY, mTheta, Dist, dLower, dUpper, iB = 1000L, dA = 0.0, dB = 1.0) {
    .Call(`_GAS_mWCRPS_backtest`, vY, mTheta, Dist, dLower, dUpper, iB, dA, dB)
}

EvaluateLogScore_Univ <- function(mTheta, vY, Dist, iT) {
    .Call(`_GAS_EvaluateLogScore_Univ`, mTheta, vY, Dist, iT)
}

EvaluateLogScore_Multi <- function(mTheta, mY, Dist, iT, iN) {
    .Call(`_GAS_EvaluateLogScore_Multi`, mTheta, mY, Dist, iT, iN)
}

ddist_univ <- function(dY, vTheta, Dist, bLog) {
    .Call(`_GAS_ddist_univ`, dY, vTheta, Dist, bLog)
}

ddist_multi <- function(vY, vTheta, iN, Dist, bLog) {
    .Call(`_GAS_ddist_multi`, vY, vTheta, iN, Dist, bLog)
}

rdist_univ <- function(vTheta, Dist) {
    .Call(`_GAS_rdist_univ`, vTheta, Dist)
}

rdist_multi <- function(vTheta, iN, Dist) {
    .Call(`_GAS_rdist_multi`, vTheta, iN, Dist)
}

pdist_univ <- function(dQ, vTheta, Dist) {
    .Call(`_GAS_pdist_univ`, dQ, vTheta, Dist)
}

qdist_univ <- function(dP, vTheta, Dist) {
    .Call(`_GAS_qdist_univ`, dP, vTheta, Dist)
}

mdist_univ <- function(vTheta, Dist) {
    .Call(`_GAS_mdist_univ`, vTheta, Dist)
}

mdist_multi_mean <- function(vTheta, Dist, iN) {
    .Call(`_GAS_mdist_multi_mean`, vTheta, Dist, iN)
}

mdist_multi_cov <- function(vTheta, Dist, iN) {
    .Call(`_GAS_mdist_multi_cov`, vTheta, Dist, iN)
}

GASFilter_univ <- function(vY, vKappa, mA, mB, iT, iK, Dist, ScalingType) {
    .Call(`_GAS_GASFilter_univ`, vY, vKappa, mA, mB, iT, iK, Dist, ScalingType)
}

GASFilter_multi <- function(mY, vKappa, mA, mB, iT, iN, iK, Dist, ScalingType) {
    .Call(`_GAS_GASFilter_multi`, mY, vKappa, mA, mB, iT, iN, iK, Dist, ScalingType)
}

uGASMultiForcast <- function(vTheta_tp1, vKappa, mA, mB, iH, iB, iK, Dist, ScalingType, bReturnsDraws) {
    .Call(`_GAS_uGASMultiForcast`, vTheta_tp1, vKappa, mA, mB, iH, iB, iK, Dist, ScalingType, bReturnsDraws)
}

mGASMultiForcast <- function(vTheta_tp1, vKappa, mA, mB, iH, iB, iK, iN, Dist, ScalingType, bReturnsDraws) {
    .Call(`_GAS_mGASMultiForcast`, vTheta_tp1, vKappa, mA, mB, iH, iB, iK, iN, Dist, ScalingType, bReturnsDraws)
}

IM_univ <- function(vTheta, Dist) {
    .Call(`_GAS_IM_univ`, vTheta, Dist)
}

Map_Vec <- function(vX, dL, dU) {
    .Call(`_GAS_Map_Vec`, vX, dL, dU)
}

unmapVec_C <- function(vG, dL, dU) {
    .Call(`_GAS_unmapVec_C`, vG, dL, dU)
}

MapParameters_univ <- function(vTheta_tilde, Dist, iK) {
    .Call(`_GAS_MapParameters_univ`, vTheta_tilde, Dist, iK)
}

UnmapParameters_univ <- function(vTheta, Dist, iK = -9999L) {
    .Call(`_GAS_UnmapParameters_univ`, vTheta, Dist, iK)
}

MapR_C <- function(vPhi, iN) {
    .Call(`_GAS_MapR_C`, vPhi, iN)
}

UnMapR_C <- function(vRho, iN) {
    .Call(`_GAS_UnMapR_C`, vRho, iN)
}

MapParameters_multi <- function(vTheta_tilde, Dist, iN, iK) {
    .Call(`_GAS_MapParameters_multi`, vTheta_tilde, Dist, iN, iK)
}

UnmapParameters_multi <- function(vTheta, Dist, iN, iK) {
    .Call(`_GAS_UnmapParameters_multi`, vTheta, Dist, iN, iK)
}

EvalMoments_univ <- function(mTheta, Dist) {
    .Call(`_GAS_EvalMoments_univ`, mTheta, Dist)
}

EvalMoments_multi <- function(mTheta, Dist, iN) {
    .Call(`_GAS_EvalMoments_multi`, mTheta, Dist, iN)
}

rmvnorm_mat <- function(iN, vMu, mSigma) {
    .Call(`_GAS_rmvnorm_mat`, iN, vMu, mSigma)
}

StaticLLK_Univ <- function(vY, vTheta, iT, Dist) {
    .Call(`_GAS_StaticLLK_Univ`, vY, vTheta, iT, Dist)
}

StaticLLK_Multi <- function(mY, vTheta, iT, iN, Dist) {
    .Call(`_GAS_StaticLLK_Multi`, mY, vTheta, iT, iN, Dist)
}

EvaluatePit_Univ <- function(mTheta, vY, Dist, iT) {
    .Call(`_GAS_EvaluatePit_Univ`, mTheta, vY, Dist, iT)
}

Quantiles <- function(mTheta, Dist, vProbs) {
    .Call(`_GAS_Quantiles`, mTheta, Dist, vProbs)
}

Score_univ <- function(dY, vTheta, Dist) {
    .Call(`_GAS_Score_univ`, dY, vTheta, Dist)
}

Score_multi <- function(vY, vTheta, iN, Dist) {
    .Call(`_GAS_Score_multi`, vY, vTheta, iN, Dist)
}

SimulateGAS_univ <- function(iT, vKappa, mA, mB, Dist, ScalingType) {
    .Call(`_GAS_SimulateGAS_univ`, iT, vKappa, mA, mB, Dist, ScalingType)
}

SimulateGAS_multi <- function(iT, iN, vKappa, mA, mB, Dist, ScalingType) {
    .Call(`_GAS_SimulateGAS_multi`, iT, iN, vKappa, mA, mB, Dist, ScalingType)
}

NumberParameters <- function(Dist, iN = 1L) {
    .Call(`_GAS_NumberParameters`, Dist, iN)
}

build_vR <- function(mR, iN) {
    .Call(`_GAS_build_vR`, mR, iN)
}

